### ISSUE TITLE
Unable to install anywhere

### ISSUE THREAD

**Issue by SmokeyOdin** [raine/tgreddit#1]
Install:
```
root@localhost:~# cargo install tgreddit
    Updating crates.io index
error: could not find `tgreddit` in registry `crates-io` with version `*`
```

Docker (After Pull):
```
root@localhost:~# docker run rainevi/tgreddit
[2023-04-03T09:33:39Z ERROR tgreddit::config] failed to read config: CONFIG_PATH environment variable not set
```

No other install info to help get this installed.

**Comment by raine** [comment]
Hey,

The `cargo install tgreddit` command should work now. I somehow forgot to publish despite documenting the install command in README.

As for `failed to read config: CONFIG_PATH environment variable not set`, you need to set `CONFIG_PATH` environment variable to path where config file is located. See https://github.com/raine/tgreddit#configuration.

For example you might run `CONFIG_PATH=./config.toml tgreddit` if you have `config.toml` in the current working directory.

Hope that helps.

**Comment by SmokeyOdin** [comment]
Hey,

Thanks for having a look at the problems so quickly!

So I got it to work after a lot of troubleshooting, one of the main problems was the example config you use kept giving me this error:

`[2023-04-03T15:19:52Z ERROR tgreddit::config] failed to read config: missing field `authorized_user_ids` at line 1 column 1`

After I edited the config file and fixed the error the bot does start - with no output to tell it everything was running, which makes me hope that all the other settings on the example config are correct and working, the other problem is your bot commands don't give enough information about how to use the bot:

/sub <subreddit> [limit=<limit>] [time=<time>] [filter=<filter>]

Limit? What's the min/max? - Time? Seconds, Minutes, Hours, Days Weeks?? - Filter? The example says videos but what are the other options? pics? pictures? links? audios?

Some more information would be great because at the moment its just replying "Something went wrong" when testing /sub and "No posts found" when using /get

Cheers

**Comment by SmokeyOdin** [comment]
After checking the terminal it did give me this error:

`[2023-04-03T15:32:41Z ERROR tgreddit::bot] failed to handle message: could not add subscription`

**Comment by raine** [comment]
> /sub [limit=] [time=] [filter=]

> Limit? What's the min/max? - Time? Seconds, Minutes, Hours, Days Weeks?? - Filter? The example says videos but what are the other options? pics? pictures? links? audios?

There's some info already in the README on these, and I added some more on the `filter`. See the comments in example configuration.

> After checking the terminal it did give me this error:
>
> `[2023-04-03T15:32:41Z ERROR tgreddit::bot] failed to handle message: could not add subscription`

And what was the command used?

**Comment by raine** [comment]
@SmokeyOdin Did you manage to get it working?
